// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use chrono::NaiveDateTime;

#[derive(Queryable, Debug, Identifiable)]
#[primary_key(start, end)]
pub struct BannedIpRange {
    pub start: Option<String>,
    pub end: Option<String>,
    pub note: Option<String>,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug, Identifiable)]
#[primary_key(channel, service)]
pub struct BannedStream {
    pub channel: String,
    pub service: String,
    pub reason: Option<String>,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive()]
pub struct Stream {
    pub id: Option<i32>,
    pub service: String,
    pub channel: String,
    pub path: Option<String>,
    pub hidden: Option<bool>,
    pub afk: Option<bool>,
    pub promoted: Option<bool>,
    pub title: String,
    pub thumbnail: Option<String>,
    pub live: Option<bool>,
    pub viewers: Option<i32>,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive()]
pub struct User {
    pub id: String,
    pub twitch_id: i64,
    pub name: String,
    pub stream_path: String,
    pub service: String,
    pub channel: String,
    pub last_ip: String,
    pub last_seen: NaiveDateTime,
    pub left_chat: Option<bool>,
    pub is_banned: bool,
    pub ban_reason: Option<String>,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub is_admin: Option<bool>,
}
